language: node_js
node_js:
  - "9"

sudo: enabled
# before_install: sudo npm install
install:
  - chmod +x ./deploy.sh
  - cd ./ziggle
  - npm install
before_script:
# script: true
script: sh ../deploy.sh

after_script:
  - echo pwd
  - cd ./public
  - git init
  - git config user.name "travis-ci"
  - git config user.email "muyue1125@gmail.com"
  - git add .
  - git commit -am "add/edit"
  - git push --force --quiet "https://${GITHUB_TOKEN}@${GH_REF}" master:master

cache:
  directroies:
    - ziggle/node_modules

git:
  depth: 2

branches:
  only:
    - master
    - /^deploy-.*$/

# deploy:
#   provider: pages
#   skip-cleanup: true
#   github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
#   keep-history: true
#   on:
#     branch: master
#     tags: true

env:
  - PACKAGE_VERSION: "1.0.1"
  - GH_REF: github.com/youngerier/youngerier.github.io
