language: node_js
node_js:
  - "9"
# before_install: sudo npm install
install:
  - npm install

# script: ./deploy.sh
script: true

git:
  depth: 2

branches:
  only:
    - master
    - /^deploy-.*$/


deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master

env:
  - PACKAGE_VERSION="1.0.1"